CREATE DATABASE EuroLeagues
USE EuroLeagues

-- Problem 1: Create
CREATE TABLE Leagues 
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Teams
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
	City NVARCHAR(50) NOT NULL,
	LeagueId INT NOT NULL,
	CONSTRAINT fk_TeamsInLeagues FOREIGN KEY (LeagueId) REFERENCES Leagues(Id)
)

CREATE TABLE Players
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	Position NVARCHAR(20) NOT NULL
)

CREATE TABLE Matches 
(
	Id INT PRIMARY KEY IDENTITY,
	HomeTeamId INT NOT NULL,
	CONSTRAINT fk_HomeTeamMatches FOREIGN KEY (HomeTeamId) REFERENCES Teams(Id),
	AwayTeamId INT NOT NULL,
	CONSTRAINT fk_AwayTeamMatches FOREIGN KEY (AwayTeamId) REFERENCES Teams(Id),
	MatchDate DATETIME2 NOT NULL,
	HomeTeamGoals INT NOT NULL DEFAULT 0,
	AwayTeamGoals INT NOT NULL DEFAULT 0,
	LeagueId INT NOT NULL,
	CONSTRAINT fk_LeaguesMatches FOREIGN KEY (LeagueId) REFERENCES Leagues(Id)
)

CREATE TABLE PlayersTeams
(
	PlayerId INT NOT NULL,
	CONSTRAINT fk_Players FOREIGN KEY (PlayerId) REFERENCES Players(Id),
	TeamId INT NOT NULL,
	CONSTRAINT fk_Teams FOREIGN KEY (TeamId) REFERENCES Teams(Id),
	CONSTRAINT pk_PlayerTeam PRIMARY KEY (PlayerId, TeamId)
)

CREATE TABLE PlayerStats
(
	PlayerId INT PRIMARY KEY,
	CONSTRAINT fk_PlayersForStats FOREIGN KEY (PlayerId) REFERENCES Players(Id),
	Goals INT NOT NULL DEFAULT 0,
	Assists INT NOT NULL DEFAULT 0
)

CREATE TABLE TeamStats
(
	TeamId INT PRIMARY KEY,
	CONSTRAINT fk_TeamsForStats FOREIGN KEY (TeamId) REFERENCES Teams(Id),
	Wins INT NOT NULL DEFAULT 0,
	Draws INT NOT NULL DEFAULT 0,
	Losses INT NOT NULL DEFAULT 0
)